all_sector_stocks = {
    "energy": {
        "XOM": "Exxon Mobil",
        "CVX": "Chevron",
        "COP": "ConocoPhillips",
        "SLB": "Schlumberger",
        "EOG": "EOG Resources",
        "MPC": "Marathon Petroleum",
        "PSX": "Phillips 66",
        "VLO": "Valero Energy",
        "OXY": "Occidental Petroleum",
        "FANG": "Diamondback Energy"
    },
    "materials": {
        "LIN": "Linde",
        "SHW": "Sherwin-Williams",
        "APD": "Air Products and Chemicals",
        "DD": "DuPont de Nemours",
        "NEM": "Newmont Corporation",
        "FCX": "Freeport-McMoRan",
        "PPG": "PPG Industries",
        "CTVA": "Corteva",
        "ECL": "Ecolab",
        "MLM": "Martin Marietta Materials"
    },
    "industrials": {
        "UNP": "Union Pacific",
        "HON": "Honeywell",
        "UPS": "United Parcel Service",
        "BA": "Boeing",
        "CAT": "Caterpillar",
        "DE": "Deere & Co.",
        "GE": "General Electric",
        "ETN": "Eaton Corp",
        "LMT": "Lockheed Martin",
        "CSX": "CSX Corporation"
    },
    "consumer_discretionary": {
        "TSLA": "Tesla",
        "AMZN": "Amazon",
        "HD": "Home Depot",
        "MCD": "McDonald's",
        "NKE": "Nike",
        "LOW": "Lowe's",
        "SBUX": "Starbucks",
        "TJX": "TJX Companies",
        "GM": "General Motors",
        "F": "Ford Motor Company"
    },
    "consumer_staples": {
        "PG": "Procter & Gamble",
        "KO": "Coca-Cola",
        "PEP": "PepsiCo",
        "WMT": "Walmart",
        "COST": "Costco",
        "MDLZ": "Mondelez",
        "CL": "Colgate-Palmolive",
        "KHC": "Kraft Heinz",
        "EL": "Estée Lauder",
        "KR": "Kroger"
    },
    "healthcare": {
        "JNJ": "Johnson & Johnson",
        "PFE": "Pfizer",
        "MRK": "Merck & Co.",
        "ABBV": "AbbVie",
        "TMO": "Thermo Fisher Scientific",
        "ABT": "Abbott Laboratories",
        "LLY": "Eli Lilly",
        "CVS": "CVS Health",
        "BMY": "Bristol Myers Squibb",
        "AMGN": "Amgen"
    },
    "financials": {
        "JPM": "JPMorgan Chase",
        "BAC": "Bank of America",
        "WFC": "Wells Fargo",
        "GS": "Goldman Sachs",
        "MS": "Morgan Stanley",
        "AXP": "American Express",
        "BK": "Bank of New York Mellon",
        "SCHW": "Charles Schwab",
        "BLK": "BlackRock",
        "TFC": "Truist Financial"
    },
    "information_technology": {
        "AAPL": "Apple",
        "MSFT": "Microsoft",
        "NVDA": "NVIDIA",
        "AVGO": "Broadcom",
        "ORCL": "Oracle",
        "ADBE": "Adobe",
        "CRM": "Salesforce",
        "AMD": "Advanced Micro Devices",
        "INTC": "Intel",
        "CSCO": "Cisco"
    },
    "communication_services": {
        "GOOGL": "Alphabet A",
        "GOOG": "Alphabet C",
        "META": "Meta Platforms",
        "DIS": "Walt Disney",
        "NFLX": "Netflix",
        "CMCSA": "Comcast",
        "VZ": "Verizon",
        "T": "AT&T",
        "CHTR": "Charter Communications",
        "TMUS": "T-Mobile"
    },
    "utilities": {
        "NEE": "NextEra Energy",
        "DUK": "Duke Energy",
        "SO": "Southern Company",
        "D": "Dominion Energy",
        "AEP": "American Electric Power",
        "EXC": "Exelon",
        "XEL": "Xcel Energy",
        "SRE": "Sempra Energy",
        "PEG": "Public Service Enterprise Group",
        "ED": "Consolidated Edison"
    },
    "real_estate": {
        "AMT": "American Tower",
        "PLD": "Prologis",
        "CCI": "Crown Castle",
        "SPG": "Simon Property Group",
        "O": "Realty Income",
        "EQIX": "Equinix",
        "WELL": "Welltower",
        "VTR": "Ventas",
        "AVB": "AvalonBay Communities",
        "EQR": "Equity Residential"
    }
}
